# Publication dataset extracted from Part B2 MSCA PF CV (Aug 2026)
# status: "published" | "review" | "prep"

PUBS = [
    # ---- Under review ----
    dict(year=2026, status="review", first=False,
         authors="McIntosh J, Sidiropoulos G, <b>Arvanitidis M</b>, Falla D",
         title="The effect of neck-specific exercise on neck muscle morphology in people with chronic neck pain: a systematic review and meta-analysis",
         journal="Musculoskeletal Science and Practice", vol="Under review", doi=None,
         topic="neck",
         note="First synthesis showing neck-specific exercise may induce structural cervical muscle adaptation."),
    dict(year=2026, status="review", first=False,
         authors="Parrella M, <b>Arvanitidis M</b>, Borzuola R, Macaluso A, Falla D",
         title="Effects of ageing on fatigue resistance and neuromuscular control of the trunk extensor muscles during isokinetic contractions",
         journal="Journal of Applied Physiology", vol="Under review", doi=None,
         topic="trunk ageing",
         note="Greater dynamic trunk extensor fatigue resistance in older adults despite poorer torque steadiness."),
    dict(year=2026, status="review", first=False,
         authors="Mendez-Rebolledo G, <b>Arvanitidis M</b>, Martinez-Valdes E",
         title="Altered neural drive to the fibularis longus during progressive loading in chronic ankle instability",
         journal="Journal of Applied Physiology", vol="Under review", doi=None,
         topic="motor unit",
         note="Load-dependent impairments in fibularis longus neural drive and motor unit rate coding."),
    dict(year=2026, status="review", first=False,
         authors="Purushotham S, Casolo A, <b>Arvanitidis M</b>, Grison A, Gardner A, Falla D",
         title="Erector spinae muscle fibre size estimation using high-density surface electromyography in people with and without non-specific chronic low back pain",
         journal="Scientific Reports", vol="Under review", doi=None,
         topic="low back pain",
         note="Non-invasive HD-sEMG approach to estimate erector spinae muscle fibre size."),
    dict(year=2025, status="review", first=False,
         authors="Contreras-Hernandez I, Falla D, <b>Arvanitidis M</b>, Negro F, Jimenez-Grande D, Martinez-Valdes E",
         title="Eccentric and concentric torque feedback training induce similar clinical improvements but distinct triceps surae motor unit adaptations in non-insertional Achilles tendinopathy: a randomised controlled trial",
         journal="Journal of Sport and Health Science", vol="Under review · preprint on medRxiv",
         doi="10.1101/2025.06.20.25330016",
         topic="tendinopathy",
         note="Similar clinical improvements but distinct neuromechanical adaptations between training modes."),

    # ---- In preparation ----
    dict(year=2026, status="prep", first=True,
         authors="<b>Arvanitidis M</b>, Cerone GL, Gazzoni M, Falla D",
         title="Real-time augmented reality biofeedback from high-density surface electromyography improves knee extensor endurance performance in humans",
         journal="British Journal of Sports Medicine", vol="In preparation", doi=None,
         topic="biofeedback",
         note="AR HD-sEMG biofeedback modified spatial muscle activation and improved knee extensor endurance by 27%."),
    dict(year=2026, status="prep", first=True,
         authors="<b>Arvanitidis M</b>, Contreras I, Negro F, Martinez-Valdes E",
         title="Assessing the interplay between neural drive and muscle contraction dynamics during postural tasks in older individuals",
         journal="The Journal of Physiology", vol="In preparation", doi=None,
         topic="motor unit ageing",
         note=None),

    # ---- 2026 ----
    dict(year=2026, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Pincheira PA, Negro F, Botter A, Cerone GL, Martinez-Valdes E",
         title="Interactions between motor unit firing and fascicle dynamics during shortening and lengthening contractions",
         journal="Journal of Neurophysiology", vol="2026", doi="10.1152/jn.00188.2026",
         topic="motor unit ultrasound",
         note="Simultaneous HD-sEMG and ultrasound via transparent electrodes revealed contraction-dependent neuromechanical coupling."),
    dict(year=2026, status="published", first=False,
         authors="Sageshima H, <b>Arvanitidis M</b>, Sidiropoulos G, River Y, Falla D",
         title="The effect of eccentric exercise-induced delayed onset neck muscle soreness on force steadiness and the spatial distribution of neck extensor muscle activity",
         journal="Scientific Reports", vol="2026", doi="10.1038/s41598-026-49353-x",
         topic="neck DOMS",
         note="Adaptive redistribution of neck muscle activity during experimentally induced soreness."),
    dict(year=2026, status="published", first=False,
         authors="Parrella M, <b>Arvanitidis M</b>, Borzuola R, Jiménez-Grande D, Macaluso A, Falla D",
         title="Age-related alterations in trunk extensor force control during isometric and isokinetic contractions",
         journal="Scientific Reports", vol="2026", doi="10.1038/s41598-026-41572-6",
         topic="trunk ageing",
         note="Age-related impairments in trunk force control with distinct HD-sEMG patterns."),
    dict(year=2026, status="published", first=False,
         authors="Thoomes EJ, <b>Arvanitidis M</b>, van Geest S, van der Windt DA, Verhagen AP, de Graaf M, Kuijper B, Scholten-Peeters GGM, Vleggeert-Lankamp CL, Falla D",
         title="Diagnostic accuracy of physical examination tests for painful cervical radiculopathy: update of a systematic review and meta-analysis",
         journal="BMC Musculoskeletal Disorders", vol="2026", doi="10.1186/s12891-026-09551-0",
         topic="neck diagnosis",
         note="Updated diagnostic accuracy evidence informing evidence-based clinical decision-making."),
    dict(year=2026, status="published", first=False,
         authors="Contreras-Hernandez I, Falla D, <b>Arvanitidis M</b>, Negro F, Jimenez-Grande D, Martinez-Valdes E",
         title="Load and muscle-dependent changes in triceps surae motor unit firing properties in individuals with non-insertional Achilles tendinopathy",
         journal="The Journal of Physiology", vol="2026;604(2):955–978", doi="10.1113/JP287588",
         topic="tendinopathy motor unit",
         note="First demonstration of load- and muscle-dependent motor unit changes in Achilles tendinopathy."),

    # ---- 2025 ----
    dict(year=2025, status="published", first=False,
         authors="Sageshima H, Parrella M, <b>Arvanitidis M</b>, Devecchi V, Falla D",
         title="Does pain alter the spatial distribution of muscle activity in people experiencing spinal pain? A systematic review and meta-analysis",
         journal="Journal of Electromyography and Kinesiology", vol="2025", doi=None,
         url="https://www.sciencedirect.com/science/article/pii/S1050641126000519",
         topic="spinal pain review",
         note="Revealed regional differences in lumbar erector spinae activity in people with spinal pain."),
    dict(year=2025, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Falla D, Negro F, Boccia G, Rainoldi A, Martinez-Valdes E",
         title="Reduced knee extensor torque steadiness and increased motor unit discharge variability in young people with patellofemoral knee pain: a pilot study",
         journal="European Journal of Applied Physiology", vol="2025", doi="10.1007/s00421-025-06083-8",
         topic="knee pain motor unit",
         note="Novel insight into neuromuscular impairments in patellofemoral pain during single-joint exercise."),
    dict(year=2025, status="published", first=False,
         authors="Parrella M, Borzuola R, Siciliano FP, <b>Arvanitidis M</b>, Nuccio S, Falla D, Piacentini MF, Macaluso A",
         title="Fatigue-induced alterations in the spatial distribution of lumbar erector spinae activity in older versus young adults",
         journal="European Journal of Applied Physiology", vol="2025;125(12):3663–3674", doi="10.1007/s00421-025-05864-5",
         topic="trunk ageing",
         note="First evidence of age-related differences in spatial lumbar activation under fatigue."),
    dict(year=2025, status="published", first=False,
         authors="Parrella M, <b>Arvanitidis M</b>, Macaluso A, Falla D",
         title="The effects of ageing on fatigue and endurance of the spinal extensor muscles: a systematic review and meta-analysis",
         journal="GeroScience", vol="2025", doi="10.1007/s11357-025-01987-x",
         topic="trunk ageing review",
         note="First meta-analysis showing reduced trunk muscle endurance in older adults."),
    dict(year=2025, status="published", first=False,
         authors="Sidiropoulos G, <b>Arvanitidis M</b>, Falla D, Kanellopoulos A, Tsekoura M, Strimpakos N, Dimitriadis Z",
         title="Association between neck muscle size and physical features in individuals with chronic non-specific neck pain: a systematic review",
         journal="Musculoskeletal Science and Practice", vol="2025;80:103428", doi="10.1016/j.msksp.2025.103428",
         topic="neck review", note=None),
    dict(year=2025, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Mak HHK, Martinez-Valdes E, Barbero M, Falla D",
         title="Validation of a novel device for assessing neck muscle strength",
         journal="Archives of Physiotherapy", vol="2025;15:148–157", doi="10.33393/aop.2025.3476",
         topic="neck measurement",
         note="The NOD is a valid, reliable, portable alternative to laboratory dynamometry."),
    dict(year=2025, status="published", first=False,
         authors="Devecchi V, <b>Arvanitidis M</b>, Falla D",
         title="Effects of microgravity on neuromuscular control of the spine: a protocol for a systematic review and meta-analysis",
         journal="BMJ Open", vol="2025;15(6):e098172", doi="10.1136/bmjopen-2024-098172",
         topic="spaceflight",
         note="Will inform countermeasures to reduce spinal pain and injury risk in astronauts."),
    dict(year=2025, status="published", first=False,
         authors="Selvamoorthy R, <b>Arvanitidis M</b>, Negro F, Pincheira P, Evans D, Martinez-Valdes E",
         title="Torque visuomotor feedback training versus standard eccentric exercise for the management of patellar tendinopathy: protocol for a randomised controlled trial",
         journal="BMJ Open", vol="2025;15(2):e092104", doi="10.1136/bmjopen-2024-092104",
         topic="tendinopathy biofeedback",
         note="First trial of torque-based visual feedback training for patellar tendinopathy."),
    dict(year=2025, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Falla D, Sanderson A, Martinez-Valdes E",
         title="Does pain influence control of muscle force? A systematic review and meta-analysis",
         journal="European Journal of Pain", vol="2025;29(2):e4716", doi="10.1002/ejp.4716",
         topic="pain force control",
         note="Force steadiness is impaired in musculoskeletal pain — a candidate rehabilitation target."),

    # ---- 2024 ----
    dict(year=2024, status="published", first=False,
         authors="Contreras-Hernandez I, <b>Arvanitidis M</b>, Falla D, Negro F, Martinez-Valdes E",
         title="Achilles tendon morpho-mechanical parameters are related to triceps surae motor unit firing properties",
         journal="Journal of Neurophysiology", vol="2024;132(4):1198–1210", doi="10.1152/jn.00391.2023",
         topic="tendinopathy motor unit",
         note="Novel link between motor unit firing behaviour and Achilles tendon mechanical properties."),
    dict(year=2024, status="published", first=False,
         authors="Corvini G, <b>Arvanitidis M</b>, Falla D, Conforto S",
         title="Novel metrics for high-density sEMG analysis in the time-space domain during sustained isometric contractions",
         journal="IEEE Open Journal of Engineering in Medicine and Biology", vol="2024;5:760–768",
         doi="10.1109/OJEMB.2024.3449548",
         topic="HD-sEMG methods",
         note="New HD-sEMG spatial metrics that characterise fatigue and predict muscle endurance."),
    dict(year=2024, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Jiménez-Grande D, Haouidji-Javaux N, Falla D, Martinez-Valdes E",
         title="Eccentric exercise-induced delayed onset trunk muscle soreness alters high-density surface EMG-torque relationships and lumbar kinematics",
         journal="Scientific Reports", vol="2024;14(1):18589", doi="10.1038/s41598-024-69050-x",
         topic="low back pain DOMS",
         note="First study of how DOMS influences trunk HD-sEMG–torque relationships and lumbar kinematics."),
    dict(year=2024, status="published", first=False,
         authors="Deane J, <b>Arvanitidis M</b>, Briggs M, Falla D, Johnson M",
         title="Evaluating the efficacy of wearable biofeedback on the outcomes of exercise interventions in people with chronic non-specific spinal pain: protocol for a systematic review and meta-analysis",
         journal="BMJ Open", vol="2024;14(7):e085206", doi="10.1136/bmjopen-2024-085206",
         topic="biofeedback", note=None),
    dict(year=2024, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Jiménez-Grande D, Haouidji-Javaux N, Falla D, Martinez-Valdes E",
         title="Low back pain-induced dynamic trunk muscle control impairments are associated with altered spatial EMG-torque relationships",
         journal="Medicine & Science in Sports & Exercise", vol="2024;56(2):193–208",
         doi="10.1249/MSS.0000000000003314",
         topic="low back pain",
         note="First evidence of impaired torque steadiness and altered HD-sEMG–torque relationships in dynamic trunk contractions in CLBP."),

    # ---- 2023 ----
    dict(year=2023, status="published", first=False,
         authors="Valencia O, Weinstein A, Salas R, Guzmán-Venegas R, <b>Arvanitidis M</b>, Martinez-Valdes E",
         title="Temporal differences in the myoelectric activity of lower limb muscles during rearfoot and forefoot running: a statistical parametric mapping approach",
         journal="European Journal of Sport Science", vol="2023;23(6):983–991", doi="10.1080/17461391.2022.2081094",
         topic="running", note=None),
    dict(year=2023, status="published", first=False,
         authors="Tsimouris D, <b>Arvanitidis M</b>, Moutzouri M, Koumantakis GA, Gioftsos G, Papandreou M, Grammatopoulou E",
         title="Is manual therapy of the diaphragm effective for people with obstructive lung diseases? A systematic review",
         journal="Respiratory Medicine and Research", vol="2023;83:101002", doi="10.1016/j.resmer.2023.101002",
         topic="respiratory", note=None),

    # ---- 2022 ----
    dict(year=2022, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Jiménez-Grande D, Haouidji-Javaux N, Falla D, Martinez-Valdes E",
         title="People with chronic low back pain display spatial alterations in high-density surface EMG-torque oscillations",
         journal="Scientific Reports", vol="2022;12(1):15178", doi="10.1038/s41598-022-19516-7",
         topic="low back pain",
         note="Novel HD-sEMG approach overcoming decomposition challenges in the lumbar erector spinae."),
    dict(year=2022, status="published", first=False,
         authors="Belavý DL, Armbrecht G, Albracht K, Brisby H, Falla D, Scheuring R, Sovelius R, Wilke HJ, Rennerfelt K, Martinez-Valdes E, <b>Arvanitidis M</b>, Göll F, Braunstein B, Kaczorowski S, Karner V, Arora NK",
         title="Cervical spine and muscle adaptation after spaceflight and relationship to herniation risk: protocol from the 'Cervical in Space' trial",
         journal="BMC Musculoskeletal Disorders", vol="2022;23(1):772", doi="10.1186/s12891-022-05684-0",
         topic="spaceflight",
         note="International project on cervical spine adaptation after spaceflight and preventive strategies for astronauts."),

    # ---- 2021 ----
    dict(year=2021, status="published", first=False,
         authors="Martinez-Valdes E, Negro F, <b>Arvanitidis M</b>, Farina D, Falla D",
         title="Pain-induced changes in motor unit discharge depend on recruitment threshold and contraction speed",
         journal="Journal of Applied Physiology", vol="2021;131(4):1260–1271", doi="10.1152/japplphysiol.01011.2020",
         topic="pain motor unit",
         note="Pain affects motor unit behaviour differently across contraction speeds."),
    dict(year=2021, status="published", first=False,
         authors="Varrecchia T, Ranavolo A, Conforto S, De Nunzio AM, <b>Arvanitidis M</b>, Draicchio F, Falla D",
         title="Bipolar versus high-density surface electromyography for evaluating risk in fatiguing frequency-dependent lifting activities",
         journal="Applied Ergonomics", vol="2021;95:103456", doi="10.1016/j.apergo.2021.103456",
         topic="occupational",
         note="HD-sEMG discriminates biomechanical risk earlier and more accurately than traditional sEMG."),
    dict(year=2021, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Bikinis N, Petrakis S, Gkioka A, Tsimpolis D, Falla D, Martinez-Valdes E",
         title="Spatial distribution of lumbar erector spinae muscle activity in individuals with and without chronic low back pain during a dynamic isokinetic fatiguing task",
         journal="Clinical Biomechanics", vol="2021;81:105214", doi="10.1016/j.clinbiomech.2020.105214",
         topic="low back pain",
         note="Altered, potentially less efficient lumbar erector spinae activation during dynamic fatigue in CLBP."),
    dict(year=2021, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Falla D, Sanderson A, Martinez-Valdes E",
         title="Does pain influence force steadiness? A protocol for a systematic review",
         journal="BMJ Open", vol="2021;11(1):e042525", doi="10.1136/bmjopen-2020-042525",
         topic="pain force control", note=None),

    # ---- 2019 ----
    dict(year=2019, status="published", first=True,
         authors="<b>Arvanitidis M</b>, Falla D, Martinez-Valdes E",
         title="Can visual feedback on upper trapezius high-density surface electromyography increase time to task failure of an endurance task?",
         journal="Journal of Electromyography and Kinesiology", vol="2019;49:102361", doi="10.1016/j.jelekin.2019.102361",
         topic="biofeedback",
         note="First study to test whether humans can selectively modify trapezius activity using HD-sEMG visual feedback."),

    # ---- 2016 ----
    dict(year=2016, status="published", first=False,
         authors="Gioftsos G, <b>Arvanitidis M</b>, Tsimouris D, Kanellopoulos A, Paras G, Trigkas P, Sakellari V",
         title="EMG activity of the serratus anterior and trapezius muscles during the different phases of the push-up plus exercise on different support surfaces and different hand positions",
         journal="Journal of Physical Therapy Science", vol="2016;28(7):2114–2118", doi="10.1589/jpts.28.2114",
         topic="shoulder", note=None),
]
